name: Update README with recent activity
on:
  schedule:
    - cron: '0 */12 * * *'   # cada 12h
  workflow_dispatch:
permissions:
  contents: write
jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: readme-activity/notifications@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          COMMIT_MSG: "chore: update recent GitHub activity"
